### ISSUE TITLE
换了你说的kit里的最新的代码，报其他错

### ISSUE THREAD

**Issue by abell123456** [shendepu/moqui-react-ssr-demo#3]
15:32:03.448 ERROR 340870931-15                      o.m.i.a.XmlAction Error running groovy script (java.lang.IllegalStateException: failed to render react session node07efz0863kb8j1fg3dz9mim12e0 in thread qtp340870931-15): 
1 : import static org.moqui.util.ObjectUtilities.*
2 : import static org.moqui.util.CollectionUtilities.*
3 : import static org.moqui.util.StringUtilities.*
4 : import java.sql.Timestamp
5 : // these are in the context by default: ExecutionContext ec, Map<String, Object> context, Map<String, Object> result
6 : 
7 :     // begin inline script
8 :     import com.moqui.ssr.React
9 : 
10 :         def reactAppCache = ec.cache.getCache('react.ssr.apps.ReactSSRDemo')
11 : 
12 :         ec.context.put('jsBrowserFileMap', reactAppCache.get('jsBrowserFileMap'))
13 :         ec.context.put('cssFileMap', reactAppCache.get('cssFileMap'))
14 : 
15 :         React react = ec.getTool("ReactSSR", React.class, "ReactSSRDemo")
16 : 
17 :         Map<String, Object> renderResult = react.render(ec.web.request);
18 : 
19 :         ec.context.put("content", renderResult.get("html") ? renderResult.get("html") : "");
20 : 
21 :         if (renderResult.get("state")) {
22 :             ec.context.put("storeState", new groovy.json.JsonBuilder(renderResult.get("state")).toString());
23 :         }
24 :     // end inline script
25 : // make sure the last statement is not considered the return value
26 : return;

15:32:03.449  WARN 340870931-15      o.moqui.i.c.TransactionFacadeImpl Rollback only not set on current transaction, status is STATUS_NO_TRANSACTION
15:32:03.449 ERROR 340870931-15                   o.m.i.w.MoquiServlet Internal error processing request: java.lang.RuntimeException: Error rendering screen [component://moqui-react-ssr-demo/screen/ReactSSRRoot/index.html.xml]
java.lang.RuntimeException: Error rendering screen [component://moqui-react-ssr-demo/screen/ReactSSRRoot/index.html.xml]
        at org.moqui.impl.screen.ScreenRenderImpl.doActualRender(ScreenRenderImpl.groovy:785) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:567) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:147) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.webapp.MoquiServlet.service(MoquiServlet.groovy:95) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[moqui_temp5921042830737600998execlib_javax.servlet-api-3.1.0.jar.:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833) ~[moqui_temp5270052018227281810execlib_jetty-servlet-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) ~[moqui_temp5270052018227281810execlib_jetty-servlet-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206) ~[moqui_temp7040773872781373566execlib_websocket-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[moqui_temp5270052018227281810execlib_jetty-servlet-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) ~[moqui_temp5270052018227281810execlib_jetty-servlet-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) ~[moqui_temp4301223163172639966execlib_jetty-security-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[moqui_temp5270052018227281810execlib_jetty-servlet-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:521) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) ~[moqui_temp483124433384347662execlib_jetty-server-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) ~[moqui_temp1166509427641871693execlib_jetty-io-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) ~[moqui_temp1166509427641871693execlib_jetty-io-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) ~[moqui_temp1166509427641871693execlib_jetty-io-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) ~[moqui_temp7820648343609945554execlib_jetty-util-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) ~[moqui_temp7820648343609945554execlib_jetty-util-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) ~[moqui_temp7820648343609945554execlib_jetty-util-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126) ~[moqui_temp7820648343609945554execlib_jetty-util-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) [moqui_temp7820648343609945554execlib_jetty-util-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) [moqui_temp7820648343609945554execlib_jetty-util-9.4.6.v20170531.jar.:9.4.6.v20170531]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IllegalStateException: failed to render react session node07efz0863kb8j1fg3dz9mim12e0 in thread qtp340870931-15
        at com.moqui.ssr.ReactRender.render(ReactRender.java:143) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React.render(React.java:102) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React$render.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.12.jar:2.4.12]
        at component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions.run(component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions:17) ~[script:?]
        at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.renderSingle(ScreenSection.groovy:132) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.render(ScreenSection.groovy:112) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenDefinition.render(ScreenDefinition.groovy:493) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.doActualRender(ScreenRenderImpl.groovy:759) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        ... 37 more
Caused by: java.lang.RuntimeException: javax.script.ScriptException: Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. in <eval> at line number 2 at column number 1671
        at com.moqui.ssr.ReactRender.render(ReactRender.java:102) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React.render(React.java:102) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React$render.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.12.jar:2.4.12]
        at component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions.run(component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions:17) ~[script:?]
        at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.renderSingle(ScreenSection.groovy:132) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.render(ScreenSection.groovy:112) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenDefinition.render(ScreenDefinition.groovy:493) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.doActualRender(ScreenRenderImpl.groovy:759) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        ... 37 more
Caused by: javax.script.ScriptException: Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. in <eval> at line number 2 at column number 1671
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:426) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:73) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:514) ~[nashorn.jar:?]
        at com.moqui.ssr.ReactRender.render(ReactRender.java:99) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React.render(React.java:102) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React$render.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.12.jar:2.4.12]
        at component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions.run(component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions:17) ~[script:?]
        at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.renderSingle(ScreenSection.groovy:132) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.render(ScreenSection.groovy:112) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenDefinition.render(ScreenDefinition.groovy:493) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.doActualRender(ScreenRenderImpl.groovy:759) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        ... 37 more
Caused by: jdk.nashorn.internal.runtime.ECMAException: Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
        at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137) ~[nashorn.jar:?]
        at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:102) ~[nashorn.jar:?]
        at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:106) ~[nashorn.jar:?]
        at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:110) ~[nashorn.jar:?]
        at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129) ~[nashorn.jar:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$1213$3248ZAAAAAAA$\^eval\_.L:2-1#r(<eval>:2) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$1212$19403A$\^eval\_.L:2-23#o(<eval>:2) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$1211$23777A$\^eval\_.L:2-26#o#L:2(<eval>:2) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$1210$6518A$\^eval\_.L:2-10#u#L:2(<eval>:2) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$1207$44790A$\^eval\_.L:3-18#o#L:3(<eval>:3) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$801$67380AAA$\^eval\_.L:4-1(<eval>:4) ~[?:?]
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:643) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
        at jdk.nashorn.internal.objects.NativeFunction.call(NativeFunction.java:192) ~[nashorn.jar:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$541$26I$\^eval\_.L:1#t(<eval>:1) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$800$33AAA$\^eval\_.L:1(<eval>:1) ~[?:?]
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:663) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
        at jdk.nashorn.internal.objects.NativeFunction.call(NativeFunction.java:192) ~[nashorn.jar:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$541$26I$\^eval\_.L:1#t(<eval>:1) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$Recompilation$798$217AA$\^eval\_.L:1#webpackJsonp(<eval>:1) ~[?:?]
        at jdk.nashorn.internal.scripts.Script$3$\^eval\_.:program(<eval>:1) ~[?:?]
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:421) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:73) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:514) ~[nashorn.jar:?]
        at com.moqui.ssr.ReactRender.render(ReactRender.java:99) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React.render(React.java:102) ~[moqui-react-ssr-0.2.jar:?]
        at com.moqui.ssr.React$render.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.12.jar:2.4.12]
        at component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions.run(component___moqui_react_ssr_demo_screen_ReactSSRRoot_index_html_xml_screen_actions:17) ~[script:?]
        at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.renderSingle(ScreenSection.groovy:132) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.render(ScreenSection.groovy:112) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenDefinition.render(ScreenDefinition.groovy:493) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.doActualRender(ScreenRenderImpl.groovy:759) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        ... 37 more
15:32:04.065  INFO 340870931-15               o.m.i.s.ScreenRenderImpl error/InternalError [] in 561ms (text/html;charset=utf-8) session node07efz0863kb8j1fg3dz9mim12e0

**Comment by shendepu** [comment]
react-redux-starter-kit 里的代码有一点过期了, react server side render代码要返回一个object `{ state, html }`,  更新都在我的项目里, 需要一点工作把最新的代码抽取出来, 等过段时间有时间时我更新一下.

**Comment by abell123456** [comment]
好的，感谢！

**Comment by abell123456** [comment]
您这边代码更新了吗？

**Comment by shendepu** [comment]
我现在有项目在赶时间，最近几个星期都没有时间看这个
