### ISSUE TITLE
failed to run with MoquiDevConf.xml not found.

### ISSUE THREAD

**Issue by simbo1905** [shendepu/moqui-react-ssr-demo#4]
As per the readme I ran:

```sh
git clone https://github.com/moqui/moqui-framework 
cd moqui-framework
gradle getComponent -Pcomponent=moqui-react-ssr
brew install gradle
git clone https://github.com/shendepu/moqui-react-ssr-demo.git runtime/component/moqui-react-ssr-demo
gradle cleanAll build load run
# Clean failed on cleanDB I ignored that assuming that it didn't exist
gradle build load run
``` 

It didn't start and gradle hung with this error:

> 21:32:32.661 ERROR         main       o.moqui.i.w.MoquiContextListener Error initializing webapp context: java.lang.IllegalArgumentException: The moqui.conf path [/Users/Shared/moqui-framework/runtime/conf/MoquiDevConf.xml] was not found.
> java.lang.IllegalArgumentException: The moqui.conf path [/Users/Shared/moqui-framework/runtime/conf/MoquiDevConf.xml] was not found.
>         at org.moqui.impl.context.ExecutionContextFactoryImpl.<init>(ExecutionContextFactoryImpl.groovy:192) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
>         at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_121]
>  

I am running: 

> MacBook-Pro:moqui-framework simon$ java -version
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
> MacBook-Pro:moqui-framework simon$ gradle -version
> 
> ------------------------------------------------------------
> Gradle 4.5.1
> ------------------------------------------------------------
> 
> Build time:   2018-02-05 13:22:49 UTC
> Revision:     37007e1c012001ff09973e0bd095139239ecd3b3
> 
> Groovy:       2.4.12
> Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
> JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
> OS:           Mac OS X 10.12.6 x86_64
> 
> MacBook-Pro:moqui-framework simon$

**Comment by shendepu** [comment]
It seems you don't have `runtime`. you may try `gradle getRuntime` or `git clone https://github.com/moqui/moqui-runtime.git runtime`

**Comment by simbo1905** [comment]
Okay this sequence of commands runs it: 

> git clone https://github.com/moqui/moqui-framework 
> cd moqui-framework/
> gradle getComponent -Pcomponent=moqui-react-ssr
> git clone https://github.com/shendepu/moqui-react-ssr-demo.git runtime/component/moqui-react-ssr-demo
> gradle getRuntime
> gradle build load run

Then it hits a different issue that I will put into a different ticket. My I suggest that the readme might benefit from including the `gradle getRuntime` which does quite a lot of work on first call?
